#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    open-in-view: false
#    properties:
#      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#  datasource:
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/test?useTimezone=true&serverTimezone=UTC
#    data-username: kakaoslide
#    data-password: slide
#  thymeleaf:
#    cache: false
#    check-template-location: true
#    template-resolver-order: 0